### ISSUE TITLE
Add copy instance button

### ISSUE THREAD

**Issue by ghost** [modrinth/theseus#609] opened 2023-08-17 08:18 UTC
### Is your suggested enhancement related to a problem? Please describe.

It would be nice to have an quick option to copy instance instead of copying it in files or exporting and adding it manually. I used to copy instance to have a "test environment" in case something goes wrong or just to find where some errors/problem is and still have backup.

### Describe the solution you'd like

Right clicking on instance show option to copy instance and after it would also show propmpt how to name the copy. The default name could be grayed out with "(copy)" sign.

**Comment by thesuzerain** [comment] 2023-09-02 08:38
Duplicate of #229

**Closed by thesuzerain** 2023-09-02 08:38 UTC
Labels: enhancement
