### ISSUE TITLE
Unable to launch any 1.20 Fabric or Quilt modpacks.

### ISSUE THREAD

**Issue by V3AI-Seven** [modrinth/theseus#252] opened 2023-06-23 22:32 UTC
### Describe the bug

When I try to load a 1.20 Fabric or Quilt instance, I get an error that says "ZipException: zip END header not found" or something similar.

### Steps to reproduce

1. Load Modrinth Launcher.
2. Create or install a new 1.20 Fabric or Quilt instance.
3. Load the instance.

### Expected behavior

I expected to be able to load the modpack.

### Additional context

https://github.com/modrinth/theseus/assets/127050193/977e63b4-042d-44a9-8a3b-48a25e6d8d0d

Video of it happening ^^^^

**Comment by triphora** [comment] 2023-06-25 17:41
Duplicate of #200

**Closed by triphora** 2023-06-25 17:41 UTC
Labels: bug
