### ISSUE TITLE
web url's and the open folder button for instances don't work

### ISSUE THREAD

**Issue by Nathan22211** [modrinth/theseus#943] opened 2023-12-17 13:49 UTC
### Describe the bug

attemping to open links in the app or open the instance folder doesn't result in anything

### Steps to reproduce

just click on the open folder button for an instance, or a web URL somewhere in the app, nothing occurs in either case

### Expected behavior

the URL should open in my default browser, or the instance folder should open in my distro's file manager

### System information

OS: Garuda Linux Drag0nized (arch based)
Kernal: linux-zen 6.6.7
app-version: 0.6.3

**Comment by triphora** [comment] 2023-12-20 05:05
Duplicate of #520

**Closed by triphora** 2023-12-20 05:05 UTC
Labels: bug
