### ISSUE TITLE
Certain popups are cut off on first click

### ISSUE THREAD

**Issue by noah-pm-dev** [modrinth/theseus#939] opened 2023-12-13 23:43 UTC
### Describe the bug

When I right-click the folder icon on a mod in a mod list, the menu popup gets cut off because it is opening off the screen. This only happens on the first right click, right clicking again repositions the popup correctly.
Minecraft is open on my monitor to the right, so you can see where it gets cut off. This also happens when there is no screen in that direction.
![image](https://github.com/modrinth/theseus/assets/112142501/fc4df6fd-57bc-4b6d-a79e-191f94a6d755)

### Steps to reproduce

1. Open an instance containing at least one mod
2. Right click the folder icon on the right hand side of one of the mods
3. The popup will open incorrectly (cut off)
4. Right click folder icon again
5. Popup will reposition to the correct spot

### Expected behavior

The popup should be positioned correctly on the first right click

### System information

Kubuntu 22.04.3 LTS | X11

### Additional context

I have only tried this on the AppImage packaging of theseus

**Comment by triphora** [comment] 2024-01-27 06:45
Duplicate of #878

**Closed by triphora** 2024-01-27 06:45 UTC
Labels: bug
