### ISSUE TITLE
Checksum validation fail

### ISSUE THREAD

**Issue by Mapty231** [modrinth/theseus#861] opened 2023-11-07 23:09 UTC
### Describe the bug

I was trying to create a 1.17 instace of vinila mc, but when i clicked create this error occured:

An error occurred
Metadata error: Failed to valid te file checksum at url https://meta.modrinth.com/minecraft/v0/versions/1.17.json with hash 708d615f4bab1930fd47535ef043036d16495ca6 after 4 tries

### Steps to reproduce

1. click on "Create Pofile"
2. select game version 1.17
3. enter any name
4. click create

### Expected behavior

A new 1.17 instance should be created

### System information

I am running windows 10 & i think i am using the latest vesrion of the launcher, i can't find a place to get teh exact version in the settings, but i always update as soon as prompted.

### Additional context

Example of creation window
![image](https://github.com/modrinth/theseus/assets/131195812/e0713e1c-6924-46e6-b4ad-7ca0495bc420)

At the same time as this i have an instance of a forge modpack runnign which i imported from the forge launcher.

**Comment by maxomatic458** [comment] 2024-01-09 14:37
same happens for me for forge 1.20.3

**Comment by wlad26** [comment] 2024-01-19 21:03
This issue should be closed as it's not a bug

**Comment by maxomatic458** [comment] 2024-01-19 21:08
> This issue should be closed as it's not a bug

Im pretty sure this is not intentional behavior.
I am unable to download Forge 1.20.3

it might just be an error in modrinths checksums

**Comment by wlad26** [comment] 2024-01-19 21:11
> > This issue should be closed as it's not a bug
> 
> Im pretty sure this is not intentional behavior. I am unable to download Forge 1.20.3
> 
> it might just be an error in modrinths checksums

This is a specific bug where Modrinth App can't create Forge 1.20.x instance because Forge has changed smth in installer
So you need to wait until Modrinth fixes it
It doesn't relate to other versions (like Vanilla 1.17 here)

**Comment by maxomatic458** [comment] 2024-01-19 21:17
i had this happen with fabric as well, but this seems to have been fixed now.

yea then this can probably be closed, because of #980

**Comment by triphora** [comment] 2024-01-27 06:17
Seems like the original issue reported by OP is now fixed.

**Closed by triphora** 2024-01-27 06:17 UTC
Labels: bug
