### ISSUE TITLE
Folder button opening desktop folder rather than the instance folder

### ISSUE THREAD

**Issue by TrinitySani** [modrinth/theseus#411] opened 2023-08-02 18:43 UTC
### Describe the bug

When going to an instance and clicking on folder it opens the desktop folder rather than the instance folder

### Steps to reproduce

1. Open any instance page
2. Click on folder
3. Modrinth App opens desktop folder

### Expected behavior

Modrinth App opening up instance folder

### Additional context

OS: Windows 11
Launcher Version: 0.3.0

**Comment by thesuzerain** [comment] 2023-08-02 18:45
Thanks for the report! This will be fixed next update

**Comment by thesuzerain** [comment] 2023-08-02 18:45
Duplicate of #382

**Closed by thesuzerain** 2023-08-02 18:45 UTC
Labels: bug
