### ISSUE TITLE
Mod Folder Button Does Nothing

### ISSUE THREAD

**Issue by SpiralshapeOfficial** [modrinth/theseus#635] opened 2023-08-19 04:06 UTC
### Describe the bug

When clicking the file location button for a jar file in a modpack it does nothing.

### Steps to reproduce

1. Click on a modpack
2. Go on the mods section
3. Click the Folder Button On The Mod Column 
![image](https://github.com/modrinth/theseus/assets/85375190/35afa960-c86f-40c1-9b3f-14bf4e85354a)

### Expected behavior

It is supposed to open the jar file's file location.

### Additional context

![image](https://github.com/modrinth/theseus/assets/85375190/958190f1-111d-41be-b64c-f327f258404d)
I am running on **Windows 10** if that helps!  (I am also on the newest version)

**Comment by thesuzerain** [comment] 2023-09-02 08:38
Duplicate of #588

**Closed by thesuzerain** 2023-09-02 08:38 UTC
Labels: bug
