### ISSUE TITLE
Tab mouseover visual bug

### ISSUE THREAD

**Issue by HaphLife** [modrinth/theseus#868] opened 2023-11-10 06:05 UTC
### Describe the bug

The mousover text does not disappear when the cursor is moved away from the tab elements.

### Steps to reproduce

1. Open app
2. Click on the "Browse" tab
3. Hover the cursor over any tab on the left hand side ("Minecraft accounts", "Home", "Browse", "Library", "Create profile", and/or "Settings")
4. Move the cursor away from that tab

### Expected behavior

It is expected that the mouseover text will disappear when the cursor is moved away from the tab elements.

### System information

I am using a Macbook with Apple Silicon

### Additional context

This only occurs after clicking on the "Browse" tab.
After clicking away from the "Browse" tab, new mouseover elements also do not disappear.

Example image of the bug:
<img width="162" alt="Screenshot 2023-11-09 at 9 49 54 PM" src="https://github.com/modrinth/theseus/assets/45584117/284974db-c6cb-4d00-a162-26c3bddad281">

**Comment by triphora** [comment] 2024-01-27 06:42
Duplicate of #829

**Closed by triphora** 2024-01-27 06:42 UTC
Labels: bug

**Comment by HaphLife** [comment] 2024-01-31 22:04
Not sure why this was closed as “not planned.” It appears to be patched for me.

**Comment by triphora** [comment] 2024-02-01 01:27
I assume you mean "it appears **not** to be patched". Like I said immediately above, this is a duplicate of #829.
