### ISSUE TITLE
App doesn't close after the first click on the X button

### ISSUE THREAD

**Issue by Felix14-v2** [modrinth/theseus#639] opened 2023-08-19 14:44 UTC
### Describe the bug

Sometimes you need to press the close button several times until the Modrinth app closes. And this isn't just a lag, if the window wasn't closed after pressing the button, it will never close until the next attempt.

### Steps to reproduce

Well... just press the button

### Expected behavior

Window should close instantly after the first click

### Additional context

Demo:

https://github.com/modrinth/theseus/assets/75726196/f6770196-7410-4277-a41d-6596142d1a8f

**Comment by zachary-caudle** [comment] 2023-08-19 21:21
You have to click on the red part of the button, for some reason it doesn't count the border as the button.

**Comment by Felix14-v2** [comment] 2023-08-20 13:56
> You have to click on the red part of the button, for some reason it doesn't count the border as the button.

It does, my recorder automatically stopped recording after closing the window, and as you can see, the demo video ends immediately after the 8th click — the window closed at that moment.

**Comment by zachary-caudle** [comment] 2023-08-21 16:24
> 

It’s weird 🤷

**Comment by Felix14-v2** [comment] 2023-11-19 18:47
Still a problem in Windows 11

https://github.com/modrinth/theseus/assets/75726196/a89db42b-1279-4d77-8705-5f489d0636f4

**Comment by triphora** [comment] 2024-01-27 06:35
Duplicate of #377

**Closed by triphora** 2024-01-27 06:35 UTC
Labels: bug
