### ISSUE TITLE
A way to copy instances.

### ISSUE THREAD

**Issue by a-person1908** [modrinth/theseus#305] opened 2023-07-01 04:11 UTC
### Is your suggested enhancement related to a problem? Please describe.

![image](https://github.com/modrinth/theseus/assets/137985347/9baa9fc7-c2c2-4bba-a8d7-34540ab6b55c)
Here's a rough mockup of how it could look.

### Additional context

I am constantly needing to manually create and copy instances and this idea sounds so useful and would speed up the process a lot!

**Comment by CodeF53** [comment] 2023-07-01 19:52
#229

**Comment by thesuzerain** [comment] 2023-07-04 16:26
Duplicate of #229

**Closed by thesuzerain** 2023-07-04 16:26 UTC
Labels: enhancement
