### ISSUE TITLE
App not launching

### ISSUE THREAD

**Issue by Peperehobbit01** [modrinth/theseus#683] opened 2023-08-28 11:23 UTC
### Describe the bug

Hey, it's the second time hear for a bug on the app, that are actually similar, because the first i repported was having the same results, and well, i think you patch it, but there is a new issues xD. So here is what i found in the program of Windows for what hapened to the app when it launch.

```
Nom du journal :Application
Source :       Application Error
Date :         28-08-23 12:32:34
ID de l’événement :1000
Catégorie de la tâche :(100)
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   Peperehobbits01
Description :
Nom de l’application défaillante Modrinth App.exe, version : 0.5.3.0, horodatage : 0x64e0451a
Nom du module défaillant : Modrinth App.exe, version : 0.5.3.0, horodatage : 0x64e0451a
Code d’exception : 0xc0000409
Décalage d’erreur : 0x00000000003f22f6
ID du processus défaillant : 0x35e4
Heure de début de l’application défaillante : 0x01d9d99af481b510
Chemin d’accès de l’application défaillante : C:\Program Files\Modrinth App\Modrinth App.exe
Chemin d’accès du module défaillant: C:\Program Files\Modrinth App\Modrinth App.exe
ID de rapport : 6886269d-96a1-4287-a575-825966ba8c3c
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 
XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-08-28T10:32:34.1649877Z" />
    <EventRecordID>454400</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Peperehobbits01</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Modrinth App.exe</Data>
    <Data>0.5.3.0</Data>
    <Data>64e0451a</Data>
    <Data>Modrinth App.exe</Data>
    <Data>0.5.3.0</Data>
    <Data>64e0451a</Data>
    <Data>c0000409</Data>
    <Data>00000000003f22f6</Data>
    <Data>35e4</Data>
    <Data>01d9d99af481b510</Data>
    <Data>C:\Program Files\Modrinth App\Modrinth App.exe</Data>
    <Data>C:\Program Files\Modrinth App\Modrinth App.exe</Data>
    <Data>6886269d-96a1-4287-a575-825966ba8c3c</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

If the first time i reported i similar bug you don't patch it, it's actully the same bug, and so sorry if this is the case if it's not, i hope you fix it soon, because i realy like Modrinth and your app is so much better, then the one made by Curseforge that is slow garbage. 

### Steps to reproduce

I don't now how tu reproduce it still, but maybe those info will help you.

Edition	Windows 10 Professionnel N
Version	21H2
Install le	‎07-‎03-‎22
Build OS	19044.3086
Experience Windows Feature Experience Pack 1000.19041.1000.0

### Expected behavior

The app to launch on the menu where i can login.

**Comment by Folas1337** [comment] 2023-09-03 18:41
Duplicate of  #571

**Closed** 2023-09-03 21:02 UTC
Labels: bug
