### ISSUE TITLE
App not opening

### ISSUE THREAD

**Issue by KorbynTalks** [modrinth/theseus#865] opened 2023-11-09 04:31 UTC
### Describe the bug

The app does not open up even tho it's a fresh install.

### Steps to reproduce

1. Run
2. Wait
3. Nothing happens

### Expected behavior

Opens normally

### System information

Windows, 16 GB of RAM, AMD Radeon RX 560 series GPU, Latest version of the app.

### Additional context

Log file:
2023-11-08T22:09:39.494288500-06:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-08T22:09:50.252658500-06:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-08T22:09:54.265294300-06:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-08T22:13:41.147263600-06:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-08T22:18:45.480009200-06:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-08T22:22:06.671882700-06:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-08T22:23:48.180902600-06:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!
2023-11-08T22:26:14.248497800-06:00  INFO theseus_gui: Initialized tracing subscriber. Loading Modrinth App!

**Comment by LukynkaCZE** [comment] 2023-11-11 12:15
https://docs.modrinth.com/faq/app/webview2

**Comment by wlad26** [comment] 2024-01-19 21:05
This issue should be closed as it's not a bug

**Comment by triphora** [comment] 2024-01-27 06:17
Please refer to https://support.modrinth.com for help.

**Closed by triphora** 2024-01-27 06:17 UTC
Labels: bug

**Comment by KorbynTalks** [comment] 2024-01-29 04:01
I fixed it after installing WebView2. Its annoying tho since I also have to install god forsaken crappy browser Edge |:

**Comment by triphora** [comment] 2024-01-29 04:06
You can install webview2 without installing Edge.
