### ISSUE TITLE
Dropdown overflow issue

### ISSUE THREAD

**Issue by ConrDev** [modrinth/theseus#366] opened 2023-07-27 09:15 UTC
### Describe the bug

![image](https://github.com/modrinth/theseus/assets/20028486/7d1bca22-cb3e-4b1d-aabe-f9ee48a565b5)

When selecting a version on the app it will overflow

### Steps to reproduce

1. go to instance settings
2. change minecraft version
3. list not fully visible

### Expected behavior

Simple fix would be that you could choose between a responsive (full) dropdown and a small dropdown

fix: https://github.com/modrinth/theseus/pull/311 (https://github.com/modrinth/omorphia/pull/77)

**Comment by thesuzerain** [comment] 2023-07-27 18:04
Thanks for your report, this will be fixed next update!

**Comment by thesuzerain** [comment] 2023-07-27 18:04
Duplicate of #211

**Closed by thesuzerain** 2023-07-27 18:04 UTC
Labels: bug
