### ISSUE TITLE
-- Useful Feedback --   Invalid Sessions & Chat Signing

### ISSUE THREAD

**Issue by jbrown1597** [modrinth/theseus#636] opened 2023-08-19 07:07 UTC
**EDIT: Latest update *appears* to have fixed the issue! <3

Game Version: 1.20.1
Launcher Version: Latest
Mod Platform: Fabric (***The issue persists in VANILLA and MODDED scenarios.***)

Bug:
1. Invalid session ID when joining my server. -- Was just working yesterday! (Fixed by re-authorizing my account in-game using the mod ReAuth. Some have reported restarting the app also works as a temporary fix, though it did not for me.)
2. In-game chat does not work. "Server refused to deliver an unsigned message." -- Was also just working yesterday! Very similar to the issue I faced with GDLauncher. It seems Microsoft doesn't like third party launchers very much (no surprise, of course.)

![01 - Copy - Copy](https://github.com/modrinth/theseus/assets/50437670/019691cb-fbda-40ab-805f-62a30ba36a93)
![02 - Copy](https://github.com/modrinth/theseus/assets/50437670/4a9dc4cd-6526-49ad-872b-e34a7979bc6f)
![03 - Copy](https://github.com/modrinth/theseus/assets/50437670/9967645d-19ba-4aaf-93bd-38ce418433e6)

Additional Info:
- I reported on this exact same issue for GDLauncher here (I used realms at the time, but the issue exists in private servers as well): https://github.com/gorilla-devs/GDLauncher/issues/1540
- ***The issue persists in VANILLA and MODDED scenarios.***

The issue is still unsolved thru GD, so I assume this isn't an easy fix - but assuming these issues are patched, this is my new de-facto launcher for life <3

### Steps to reproduce

1. Start Modrinth Launcher
2. Make sure I am logged in via Microsoft Account
4. Start game
5. Attempt to join server
6. Receive error: Invalid Session ID, please try restarting
7. Reauthorize using mod ReAuth
8. Join server
9. Type something in chat
10. Receive error about unsigned messaged, failed to deliver.

**Comment by Fnige** [comment] 2023-08-19 07:51
Just making sure, you dont have any mods like no chat reports or similar within your modlist right?

**Comment by jbrown1597** [comment] 2023-08-19 12:14
> Just making sure, you dont have any mods like no chat reports or similar within your modlist right?

- When launching a vanilla instance: I am unable to connect in general. 
- When launching a modded instance WITH mods such as no chat reports: I cannot connect to my server in general, unless bypassed via mod. THEN, I recieve the error message from the original post.
- When launching a modded instance WITHOUT mods such as no chat reports: I cannot connect to my server in general, thus I am unsure.

**Comment by jbrown1597** [comment] 2023-08-19 12:21
> Just making sure, you dont have any mods like no chat reports or similar within your modlist right?

Just edited the post right after your reaction, check it out! Appears I was wrong on the chat part.

**Comment by Felix14-v2** [comment] 2023-08-19 14:23
Can confirm, I encountered the same issue yesterday after logging in on 2nd device. But so far I can't reproduce the problem.

**Comment by Geometrically** [comment] 2023-08-21 22:44
This should be fixed now. let me know if this is still a problem

**Closed by Geometrically** 2023-08-21 22:44 UTC
Labels: bug

**Comment by bskogman** [comment] 2024-01-03 06:30
I'm getting the missing profile public key error still. 1.20.1 on a private server, latest GDLauncher. Chat works when using the CurseForge launcher to connect.
