### ISSUE TITLE
I got logged out of the Modrinth launcher, and can't log back in

### ISSUE THREAD

**Issue by DakotaPride** [modrinth/theseus#583] opened 2023-08-13 19:31 UTC
### Describe the bug

Error popup I recieve: 
<img width="231" alt="error" src="https://github.com/modrinth/theseus/assets/82760983/88750f9a-9e38-4d5f-87b2-3d473b8824de">

I loaded the launcher and then tried to open a modpack that I have installed, it then told me that I needed to log in (it looked like I already was, so I restarted the launcher initially) and then in the top-left, I wasn't signed into Microsoft. So I clicked on the player icon and tried to sign in, giving me the error provided above once I had selected my Microsoft account

### Steps to reproduce

1. (if signed out) Select the player icon and hit the sign in button provided via the popup
2. Select your account to play with
3. Error may popup in bottom right of the screen (not sure if this is a one-time issue/if it's just me)

### Expected behavior

I expected to open a custom modpack to play on a private Create mod server, of which failed to load (because I wasn't signed in). I then expected to sign in easily, until the error provided popped up after the process.

### Additional context

Note: In the settings, it says that I am signed in with my Github account (the one that I use for Modrinth in the web browser)
<img width="1175" alt="image" src="https://github.com/modrinth/theseus/assets/82760983/a5b59e77-f8a3-4407-b95e-55e1c05ce2f3">

**Comment by DakotaPride** [comment] 2023-08-13 19:44
After attempting to sign in a couple more times, it worked. But this should still be looked into, as it is still odd behaviour I believe.

**Comment by TheAlan404** [comment] 2023-08-14 16:45
duplicate of #517

**Comment by thesuzerain** [comment] 2023-08-28 19:27
Thanks! should be fixed with the login changes

**Closed** 2023-08-28 19:27 UTC
Labels: bug
