### ISSUE TITLE
Update all mods in the instance with one button.

### ISSUE THREAD

**Issue by Boloral** [modrinth/theseus#597] opened 2023-08-15 13:52 UTC
### Is your suggested enhancement related to a problem? Please describe.

It's not convenient to update mods manually because, for example, some cool new feature appeared and you don't want to manually download the mod again, and if a new feature is added, you just click one button and all the mods are updated to the newest possible version of your Minecraft.

### Describe the solution you'd like

Update all mods in the instance to the newest possible version for your Minecraft with one mouse click, and I would also like to have automatic update of all mods.

### Additional context

Automatic update of all mods if I'm not mistaken is on "CurseForge Launcher".

**Comment by ZesilinaNewborn** [comment] 2023-08-15 14:19
Duplicate of #589 btw i believe

**Closed** 2023-08-16 06:36 UTC
Labels: enhancement
