### ISSUE TITLE
MACos crash

### ISSUE THREAD

**Issue by Julieisbaka** [modrinth/theseus#446] opened 2023-08-04 00:31 UTC
### Describe the bug

macos catlina 10.15.7 macbook pro mid 2012
modrinth app crashed when opening

### Steps to reproduce

use a macos catilina 10.15.7
macbook pro mid 2012
open modrinth

### Expected behavior

modrinth opens

**Comment by Julieisbaka** [comment] 2023-08-04 00:34
is it safe for me to leave a copy of the crash text or is that pottentially dangerous

**Comment by thesuzerain** [comment] 2023-08-04 02:33
how far into the process did it get? Did the app fully open?
If your crash text has no personal information (your name, username, etc) it should be OK to post

**Comment by Julieisbaka** [comment] 2023-08-04 21:54
no it didnt even open, k here is the info

Process:               Modrinth App [1222]
Path:                  /Applications/Modrinth App.app/Contents/MacOS/Modrinth App
Identifier:            com.modrinth.theseus
Version:               0.3.1 (20230803.175250)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Modrinth App [1222]
User ID:               501

Date/Time:             2023-08-04 17:54:07.148 -0400
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        21D5A598-A039-9A02-EF96-61316EDC5BDC

Sleep/Wake UUID:       7CC9C416-77FB-4F79-BD8A-936DE8398FEF

Time Awake Since Boot: 740 seconds
Time Since Wake:       500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Applications/Modrinth App.app/Contents/MacOS/Modrinth App
  Reason: image not found

Binary Images:
       0x10ad75000 -        0x10b8b4ff3 +com.modrinth.theseus (0.3.1 - 20230803.175250) <76F4E545-EC86-3759-9EAC-21D6B5C0F711> /Applications/Modrinth App.app/Contents/MacOS/Modrinth App
       0x118af1000 -        0x118b83267  dyld (750.7) <9F48F7F8-94D0-3793-99B7-DDEF657EF956> /usr/lib/dyld
    0x7fff333de000 -     0x7fff3385eff9  com.apple.CoreFoundation (6.9 - 1678.104) <CA9600EB-C7BE-38C4-968D-4BF90B1C9550> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff347eb000 -     0x7fff347ebfff  com.apple.CoreServices (1069.28 - 1069.28) <45131B9C-99AA-340E-947F-E53F2C829F20> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff35ac3000 -     0x7fff35e88ff7  com.apple.Foundation (6.9 - 1678.104) <69B915AD-CE6F-3958-8E3A-9D6050989AC2> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff40c45000 -     0x7fff40cbfff7  com.apple.SystemConfiguration (1.19 - 1.19) <D3494EFE-F392-379E-B21C-0F1B094ECE77> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff6be50000 -     0x7fff6be82fde  libobjc.A.dylib (787.1) <265783CE-6D74-36C9-B6D2-95D3910199EC> /usr/lib/libobjc.A.dylib

Model: MacBookPro9,2, BootROM 429.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.5 GHz, 8 GB, SMC 2.2f44
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54333531533643465238432D50422020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54333531533643465238432D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.21.190.33 AirPortDriverBrcm4360-1601.1)
Bluetooth: Version 7.0.6f8, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: MTFDDAK256MAY-1AH12ABHA, 256.06 GB
Serial ATA Device: MATSHITADVD-R   UJ-8A8
USB Device: USB 3.0 Bus
USB Device: USB Receiver
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

**Comment by Geometrically** [comment] 2023-08-05 21:13
this is a duplicate of a another issue, the launcher currently crashes on catalina

**Closed by Geometrically** 2023-08-05 21:13 UTC
Labels: bug
