### ISSUE TITLE
Already installed Minecraft mods are sometimes not marked as installed

### ISSUE THREAD

**Issue by Libroru** [modrinth/theseus#557] opened 2023-08-10 18:28 UTC
### Describe the bug

When browsing Minecraft mods they sometimes don't show up as installed as long as they are not on the first page when clicking discover.

### Steps to reproduce

Have a mod installed that is on the top of the first page (e.g. Sodium).
Change filters or change pages to another page (2-9) and then switch back to the first page.

### Expected behavior

Already installed mods show up correctly as installed.

**Comment by thesuzerain** [comment] 2023-08-10 22:52
Duplicate of #509

**Closed** 2023-08-11 01:15 UTC
Labels: bug
