### ISSUE TITLE
Running instances are not visible after closing the app

### ISSUE THREAD

**Issue by ghost** [modrinth/theseus#606] opened 2023-08-16 21:13 UTC
### Describe the bug

Running instances are not visible after closing the app. I think it shoul be like in other launchers for exaple Prism that I have used before. 

### Steps to reproduce

1. Open Modrinth App
2. Run one or more instances
3. Close app
4. Run Modrinth App again 
5. No instances running is shown

### Expected behavior

1. Open Modrinth App
2. Run one or more instances
3. Close app
4. Run Modrinth App again
5. Instances that still running are shown in app

**Comment by thesuzerain** [comment] 2023-08-28 16:03
Duplicate of #272

**Closed by thesuzerain** 2023-08-28 16:03 UTC
Labels: bug
