### ISSUE TITLE
Folder button doesnt open actual location

### ISSUE THREAD

**Issue by Kxffie** [modrinth/theseus#413] opened 2023-08-02 22:25 UTC
### Describe the bug

When clicking the "Folder" button on your custom instance, it opens your home directory and not the app.

### Steps to reproduce

1. Click the folder button on your instance

### Expected behavior

Open the instance directory

**Comment by thesuzerain** [comment] 2023-08-02 22:27
thanks for your report! This will be fixed next update

**Comment by thesuzerain** [comment] 2023-08-02 22:27
Duplicate of #382

**Closed by thesuzerain** 2023-08-02 22:27 UTC
Labels: bug
