### ISSUE TITLE
Web browser opening with default GTK theme

### ISSUE THREAD

**Issue by TheSuperGamer20578** [modrinth/theseus#674] opened 2023-08-26 02:03 UTC
### Describe the bug

I have Google Chrome set to use my GTK theme. When I click any links in the app it opens Google Chrome using the default GTK theme. Other applications such as Discord open Chrome with the correct GTK theme as expected.

### Steps to reproduce

Click on any link that opens a web browser while the web browser is closed (so that it starts a new process)

### Expected behavior

My web browser opens with the correct GTK theme.

**Comment by triphora** [comment] 2024-01-27 06:33
Duplicate of #480

**Closed by triphora** 2024-01-27 06:33 UTC
Labels: bug
