### ISSUE TITLE
Folder button broken.

### ISSUE THREAD

**Issue by Classic16** [modrinth/theseus#382] opened 2023-07-28 03:04 UTC
### Describe the bug

Whenever i click on the folder button on my modpack, It doesn't send me to the instance's folder, It just sends me to the main menu of the files home screen.

### Steps to reproduce

1. Go to your modpack instance.
2. Click the folder button on your modpack.

**Comment by SpiralshapeOfficial** [comment] 2023-07-28 03:18
Duplicate of #369  btw

**Comment by CodeF53** [comment] 2023-08-01 17:48
## Expected behavior:
System's file explorer opens to `...\com.modrinth.theseus\profiles\UUID\`

## Actual Behavior:
System's file explorer opens to Desktop

## Additional context:
Windows 11

App Version 0.3.?? (impossible to tell, not shown anywhere in the app)

**Closed** 2023-08-03 17:30 UTC
Labels: bug
