### ISSUE TITLE
When editing the version and launcher of a instance, it doesn't show 1.20.1 and hardly shows 1.20 because it won't scroll all the way up

### ISSUE THREAD

**Issue by CommandBlockGuru** [modrinth/theseus#351] opened 2023-07-21 04:07 UTC
### Describe the bug

I'm trying to edit one of my MC instances to the most recent version because I had to have it on 1.19 as the 1.20 versions did not work until a recent patch, and I found that the place where you go to edit the game version does not scroll up all the way and doesn't show the top of the selections. It shows a tiny bit of the 1.20 but doesn't show or let me click on 1.20.1 at all.

### Steps to reproduce

1. Select an instance
2. Go to options
3. Click "Edit mod loader/game versions"
4. Select the game version to change it
5. Scroll all the way up

### Expected behavior

I expect it to show all the options properly and allow me to select 1.20.1 as my version to play on.

### Additional context

![Screenshot (122)](https://github.com/modrinth/theseus/assets/68716063/87b43b43-ef84-4c74-b0cf-16d02738c370)
(In the image, I am scrolled all the way to the top of the setting, I tried to submit a video but it didn't let me, I'll try again if you need it)

**Comment by thesuzerain** [comment] 2023-07-26 16:40
Duplicate of #211

**Comment by thesuzerain** [comment] 2023-07-26 16:40
Thanks for your report, this will be fixed next update!

**Closed by thesuzerain** 2023-07-26 16:40 UTC
Labels: bug
