### ISSUE TITLE
Incompatibility warning Visual Bug

### ISSUE THREAD

**Issue by Spacewalker2307** [modrinth/theseus#244] opened 2023-06-23 08:32 UTC
### Describe the bug

When you get the Incompatibility warning you can choose from different versions but the Version at the top gets cut off.

### Steps to reproduce

1. Make a new Project or download one 
2. Click on "Add Content"
3. Search a Mod that isnt updatet yet to this version
4. Try to download it
5. You get the Incompatibility warning popup with the visual bug

### Expected behavior

I can see the first version too.

**Comment by rbits0** [comment] 2023-06-23 09:08
Screenshot:
![image](https://github.com/modrinth/theseus/assets/56014573/38b89a01-8ad0-48ad-84c2-19e6903eec16)

Tested with the .deb version

**Comment by Spacewalker2307** [comment] 2023-06-23 09:35
> Screenshot: ![image](https://user-images.githubusercontent.com/56014573/248225263-38b89a01-8ad0-48ad-84c2-19e6903eec16.png)
> 
> Tested with the .deb version
![Screenshot 2023-06-23 112607](https://github.com/modrinth/theseus/assets/137490357/cee5e4ec-20e3-4630-ac54-77f5189ac16d)

I cant scroll up

**Comment by Spacewalker2307** [comment] 2023-06-23 09:36
![Screenshot 2023-06-23 112607](https://github.com/modrinth/theseus/assets/137490357/4199211e-6eed-4afb-9ea4-c7893e93555a)

I cant scroll up

**Comment by CodeF53** [comment] 2023-06-23 23:53
Same issue as #211, seems like this is a problem for all dropdowns in modals

**Comment by triphora** [comment] 2023-06-24 00:00
Duplicate of #211

**Closed by triphora** 2023-06-24 00:00 UTC
Labels: bug
