### ISSUE TITLE
Cant run modrinth on  Mac

### ISSUE THREAD

**Issue by Codex1120** [modrinth/theseus#383] opened 2023-07-28 10:19 UTC
### Describe the bug

Modrinth gives the following error on mac:
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 0781246A-4850-3632-8FD5-CCB70AA8F9B8
Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /private/var/folders/*/Modrinth App.app/Contents/MacOS/Modrinth App
  Reason: image not found

It also said to check if the apps work with this version of mac, I am on Big Sur

### Steps to reproduce

1. Download Modrinth
2. Try to open app

### Expected behavior

For the app to open

**Comment by Geometrically** [comment] 2023-07-28 19:54
duplicate of another issue

**Closed by Geometrically** 2023-07-28 19:54 UTC
Labels: bug
