### ISSUE TITLE
instance folder opens "This PC" folder instead of instance folder

### ISSUE THREAD

**Issue by legoaggelos** [modrinth/theseus#417] opened 2023-08-03 07:32 UTC
### Describe the bug

I go to see the files of a modpack, but when clicking the instance folder it goes to the "This PC" folder.(I have a video of it happening here and in the steps to reproduce)

https://github.com/modrinth/theseus/assets/130144598/01457ef2-f4b8-4da0-9fb7-f9d0c6a1eaee

### Steps to reproduce

https://github.com/modrinth/theseus/assets/130144598/a1a7cf24-9624-45bb-9cd0-983b6ca7ba61

1. go to an instance
2. click "open instance"
3. it goes to the "This PC" folder

### Expected behavior

should open the instance of the modpack

### Additional context

i have updated from 0.2.0->0.3.0 using the notification in the app.

**Comment by legoaggelos** [comment] 2023-08-03 07:33
r

**Comment by legoaggelos** [comment] 2023-08-03 07:34
same to #382

**Comment by thesuzerain** [comment] 2023-08-03 17:41
Duplicate of #382

**Closed by thesuzerain** 2023-08-03 17:41 UTC
Labels: bug
