### ISSUE TITLE
Exporting My Profile makes an empty file

### ISSUE THREAD

**Issue by Pro42good** [modrinth/theseus#883] opened 2023-11-18 22:24 UTC
### Describe the bug

Makes a non usable mr pack file when export a profile

### Steps to reproduce

1. Go to profile that you want to export
2. Click the export and export it into a folder
3.  File shows as a non existent/ empty file

### Expected behavior

Non Usable file made

### System information

Windows
Processor	Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
Installed RAM	12.0 GB (11.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Modrinth 0.6.1

### Additional context

![image](https://github.com/modrinth/theseus/assets/119337293/f8198199-8f86-45cc-b92a-c7a9ff8b8200)

**Comment by wlad26** [comment] 2024-01-19 21:58
Can't reproduce on Windows 11 and App version 0.6.3

**Comment by triphora** [comment] 2024-01-27 06:33
Closing per above

**Closed by triphora** 2024-01-27 06:33 UTC
Labels: bug
