### ISSUE TITLE
Updating Mods

### ISSUE THREAD

**Issue by Edeec0** [modrinth/theseus#319] opened 2023-07-07 11:17 UTC
### Describe the bug

when i try updating mods it wont work i need to uninstall it the install it agian

### Expected behavior

I expected the updating feature to work and not for it to take 60+ years and still not work

**Comment by ludverse** [comment] 2023-07-07 19:42
duplicate and already fixed till next release

**Comment by CodexAdrian** [comment] 2023-07-21 03:36
Duplicate of #313

**Closed by CodexAdrian** 2023-07-21 03:36 UTC
Labels: bug
