### ISSUE TITLE
Search Parameters do not persist after page back

### ISSUE THREAD

**Issue by Cptn-Sherman** [modrinth/theseus#910] opened 2023-11-25 05:26 UTC
### Describe the bug

When performing a page back with a active search where the sort by type is not `Relevance` the sort reverts to `Relevance`. 

My expectation was that if I change the `sort by` or any other type of search parameters they will stick after loading a page and attempt to return back to the search. Feels annoying to have to change the `sort by` method every time or be unable to read more about a potential mod I may install.

### Steps to reproduce

1. Open a mod pack
2. Click add content
3. Change sort by to anything other than Relevance
4. Click on any mod to open its main page
5. Click back at the top left

### Expected behavior

The `sort by` type remains the same after backing out of mod page.

**Comment by triphora** [comment] 2024-01-27 06:38
Duplicate of #646

**Closed by triphora** 2024-01-27 06:38 UTC
Labels: bug
