### ISSUE TITLE
Microsoft login bug

### ISSUE THREAD

**Issue by Michax777** [modrinth/theseus#215] opened 2023-06-21 19:05 UTC
### Describe the bug

![obraz](https://github.com/modrinth/theseus/assets/40125094/a0e35b3c-1217-4955-b288-70b7eac2a4cd)

### Steps to reproduce

1. Click offline accounts
2. Login
3. Get window login successful
4. nothing changes
5. get error

### Expected behavior

login to account

**Comment by thesuzerain** [comment] 2023-07-04 16:23
Marking as the same bug as #293 (even though you were first). Thanks for the report

**Comment by thesuzerain** [comment] 2023-07-04 16:23
Duplicate of #293

**Comment by thesuzerain** [comment] 2023-07-04 16:23
Duplicate of #293

**Closed by thesuzerain** 2023-07-04 16:23 UTC
Labels: bug
