### ISSUE TITLE
Folder name com.modrinth.theseus breaks Structure Block's file creation in Vanilla

### ISSUE THREAD

**Issue by Yetenol** [modrinth/theseus#857] opened 2023-11-06 21:34 UTC
### Describe the bug

When I click `SAVE` in a structure block in *Save Mode*, it throws `Unable to save structure 'minecraft:test'` in the chat.
I was able to fix the error by renaming Modrinth's app directory from `com.modrinth.theseus` to `.modrinth`.
Can you change the default app directory name, so other players don't run into the save issue?

The [structure block](https://minecraft.wiki/w/Structure_Block) exports up to 32x32x32 block into an NBT file like 
```
%AppData%\com.modrinth.theseus\profiles\Vanilla\saves\New World\generated\minecraft\structures\test.nbt
```

### Steps to reproduce

- Open Modrinth App
- Launch a Vanilla 1.20.2 instance 
- Create a new creative world
- Place a structure block and change it to *Save Mode*
    ```
    /setblock ~ ~ ~ minecraft:structure_block[mode=save]
    ```
- Enter a structure name and click `SAVE`
    ![image](https://github.com/modrinth/theseus/assets/28755326/8493f0fc-fe91-4526-a9da-099fe0ccde25)
- The error `Unable to save structure 'minecraft:test'` appears in chat

### Expected behavior

When I click `SAVE` in a minecraft structure block, a message `Structure saved as 'minecraft:test'` should appear in chat and the following file should be created:

```
%AppData%\com.modrinth.theseus\profiles\Vanilla\saves\New World\generated\minecraft\structures\test.nbt
```

### System information

I run Modrinth App 0.6.0 on Microsoft Windows 11 Pro 10.0.22621 Build 22621

**Comment by Yetenol** [comment] 2023-11-06 21:37
This issue also occurs in other Minecraft distributions:
https://github.com/flathub/com.mojang.Minecraft/issues/64
https://www.reddit.com/r/MinecraftHelp/comments/15obirr/i_cannot_save_structure_using_structure_blocks/

**Comment by Yetenol** [comment] 2023-11-06 21:42
Similar to #682 but I the *read-only* wasn't a problem

**Comment by Yetenol** [comment] 2023-11-06 21:44
Until there is a more intended solution, here is how to fix it:

- Close Minecraft and Modrinth
- Navigate to `%AppData%` in File Explorer
- Backup Modrinth's app directory `com.modrinth.theseus`
- Rename `com.modrinth.theseus` to `.modrinth`
- Open Modrinth and skip the welcome screen and tutorial
- Open Modrinth's settings and change to app directory to `%AppData%/.modrinth`
- Launch your Minecraft instance again and click save in any structure block

**Comment by rowandevving** [comment] 2023-12-16 20:58
can confirm on minecraft 1.20.4 and theseus v0.6.3

**Comment by Sketano** [comment] 2024-01-20 12:31
Please fix this issue, I cannot save structures.

**Comment by ManicQuinn** [comment] 2024-01-24 08:13
> Until there is a more intended solution, here is how to fix it:
> 
> * Close Minecraft and Modrinth
> * Navigate to `%AppData%` in File Explorer
> * Backup Modrinth's app directory `com.modrinth.theseus`
> * Rename `com.modrinth.theseus` to `.modrinth`
> * Open Modrinth and skip the welcome screen and tutorial
> * Open Modrinth's settings and change to app directory to `%AppData%/.modrinth`
> * Launch your Minecraft instance again and click save in any structure block

This temporary fix breaks Modrinth's built-in Java, hope they will fix this soon..

**Comment by triphora** [comment] 2024-01-27 06:44
Duplicate of #682

**Closed by triphora** 2024-01-27 06:44 UTC
Labels: bug

**Comment by caleb53575Scratch** [comment] 2024-04-28 14:14
[](https://github.com/modrinth/theseus/issues/857#issuecomment-1796597158) I tried it and now I can't open any of my mod packs. Thanks for making me lose months of progress on multiple worlds, idiot.

**Comment by caleb53575Scratch** [comment] 2024-04-28 14:16
[Refrence](https://github.com/modrinth/theseus/issues/857#issuecomment-1796597158) I tried it and now I can't open any of my mod packs, even after reverting all changes. Thanks for making me lose months of progress on multiple worlds, idiot.

**Comment by LukaM01** [comment] 2024-06-29 20:32
That happend to me too now I can't access my modpacks , I think I know how to fix it. I will comment the solution once I find it

**Comment by GreedyAllay** [comment] 2024-07-21 14:56
NOOOO ME TOO I lost everything!!!!!

**Comment by GreedyAllay** [comment] 2024-07-21 14:57
Losing everything only for a fucking whore structure is insane

**Comment by blryface** [comment] 2024-07-21 18:28
what the hell

**Comment by J0B10** [comment] 2024-08-20 11:45
> https://github.com/modrinth/theseus/issues/857#issuecomment-1796597158 I tried it and now I can't open any of my mod packs, even after reverting all changes. Thanks for making me lose months of progress on multiple worlds, idiot.

For me, reloctaing modrinth to a different drive (`D:\ModrinthData`) using the option in the settings fixed the issue.

**Also dont forget to make a backup. If you forget about it don't complain when losing any data!**
