### ISSUE TITLE
External links not opening

### ISSUE THREAD

**Issue by Ryhon0** [modrinth/theseus#542] opened 2023-08-09 17:35 UTC
### Describe the bug

Clicking any button which opens a link in the web browser fails with the following message being printed to the web console:
```
shell error: failed to open: Scoped shell IO error: exit status: 3
G2 — index-ab5ceace.js:1:14541
Sa — index-ab5ceace.js:1:14494
(anonymous function) — index-ab5ceace.js:1:14152
enqueueJob
(anonymous function)
enqueueJob
(anonymous function) — Anonymous Script 1 (line 288)
value — Anonymous Script 1 (line 259)
Global Code — Script Element 6:3
Global Code — sop:3
```

### Steps to reproduce

1. Click on any mod or mod pack or attempt to log in to Modrinth using an eternal account.

### Expected behavior

The link opens in a web browser

### Additional context

Running the AppImage release on Arch Linux
App version: 0.5.0

**Comment by triphora** [comment] 2023-12-20 05:02
Duplicate of #520

**Closed by triphora** 2023-12-20 05:02 UTC
Labels: bug
