### ISSUE TITLE
(Arch Linux) Login troubles with AppImage

### ISSUE THREAD

**Issue by XDuskAshes** [modrinth/theseus#707] opened 2023-09-01 19:20 UTC
### Describe the bug

The bug is that the actual usage of the AppImage (specifically on the web auth side) is basically out of the window. First off, none of the "open link" buttons work, and the error that pops up in terminal after an attempt to login with my Microsoft account is:
``** (modrinth-app:2726): WARNING **: 14:19:20.702: atk-bridge: get_device_events_reply: unknown signature``

Not only that, none of the login buttons to sign-in to my Modrinth account work.

### Steps to reproduce

Try to use the login items.

### Expected behavior

The app to be able to open links and auth proper.

**Comment by Schweeeeeeeeeeeeeeee** [comment] 2023-09-03 17:51
Please fix :/ :(

**Comment by Madis0** [comment] 2023-09-05 20:09
Can confirm. For me, skipping the tutorial worked though, as it figured out it has been authenticated after that process.

**Comment by triphora** [comment] 2023-12-20 05:03
Duplicate of #520

**Closed by triphora** 2023-12-20 05:03 UTC
Labels: bug
