### ISSUE TITLE
Quilt and fabric mods

### ISSUE THREAD

**Issue by crystalclean69** [modrinth/theseus#558] opened 2023-08-10 18:42 UTC
### Describe the bug

Fabric mods do work on quilt, but i can't install them? they won't show up

### Steps to reproduce

1. Create quilt instance
2. Search for fabric mods (there's none)

### Expected behavior

Fabric mods show up and i can install them

**Comment by CodexAdrian** [comment] 2023-08-10 21:54
Duplicate of #488

**Closed by CodexAdrian** 2023-08-10 21:54 UTC
Labels: bug
