### ISSUE TITLE
Switching between browsing categories causes results to never load (Mac)

### ISSUE THREAD

**Issue by Oslypsis** [modrinth/theseus#169] opened 2023-06-21 04:18 UTC
### Describe the bug

On Mac Ventura 13.4
Clicking "Browse" on the left side will successfully open the browsing for "Modpacks" but clicking "Mods" "Data Packs" "Shaders" or "Resource Packs" will cause an indefinite loading screen where the results should be. Clicking back on "Modpacks" will cause an indefinite loading screen as well. Switching from "Browse" to "Library" or "Home" and back will cause the "Modpacks" results to load again.

### Steps to reproduce

Open app
Click on "Browse" on left hand side
Click on any of the other categories besides "Modpacks"
Error occurs

### Expected behavior

Expected results to load for each category.

### Additional context

https://i.imgur.com/FyJpNr0.png

**Comment by Geometrically** [comment] 2023-06-21 15:06
this is a duplicate of another issue

**Closed** 2023-06-21 15:07 UTC
