### ISSUE TITLE
Modpack Filter While On Seperate Page

### ISSUE THREAD

**Issue by TheMasterKitty** [modrinth/theseus#955] opened 2023-12-23 21:40 UTC
### Describe the bug

When you are in the ModPack display and switch the filter from All > something else and are on a higher page than the maximum for the new filter, it just removes the page options and shows a blank list of items.

### Steps to reproduce

Go into a modpack with for example 2 pages and 1 resource pack, go to the 2nd page, and switch the view filter from all to Resource Packs. This is fixed with search but not with this filter.

### Expected behavior

It should switch you to the highest page possible of resource packs (or whichever filter), for the given example page 1.

### System information

Windows and Latest (0.6.3)

### Additional context

![image](https://github.com/modrinth/theseus/assets/109026259/8763736e-5799-4788-a4f0-52d363e429dc)
![image](https://github.com/modrinth/theseus/assets/109026259/af126567-2555-48ec-bbd7-12e4f575c9dd)
![image](https://github.com/modrinth/theseus/assets/109026259/ae1bf7c5-5682-4ccc-a14e-00739db21dc5)
![image](https://github.com/modrinth/theseus/assets/109026259/9d016b42-be12-44cf-9252-4ef8c9b3cfba)

**Comment by triphora** [comment] 2024-01-27 06:40
Duplicate of #726

**Closed by triphora** 2024-01-27 06:40 UTC
Labels: bug
