### ISSUE TITLE
Mod Authors in the Mod Pages

### ISSUE THREAD

**Issue by WaffleyAero** [modrinth/theseus#655] opened 2023-08-21 21:50 UTC
### Describe the solution you'd like

When you're inside a mod page on the app, on the left side there should be an author button for who made the mod. You could click the button and view all the content that the author has published

### Describe alternatives you've considered

Searching by author but someone may have already suggested that. Otherwise, no I haven't really thought of any that could work similarly.

**Comment by triphora** [comment] 2023-09-15 02:16
Duplicate of #483

**Closed by triphora** 2023-09-15 02:16 UTC
Labels: enhancement
