### ISSUE TITLE
Not showing latest Quilt versions

### ISSUE THREAD

**Issue by Treetrain1** [modrinth/theseus#856] opened 2023-11-06 01:47 UTC
### Describe the bug

When selecting a version of Quilt Loader, it shows the latest is 0.21.1 beta 2, but the latest is 0.22.0 beta 1

### Steps to reproduce

1. Create new instance
2. Select 1.20.1 or 1.20.2 and quilt loader
3. Show advanced, other
4. look at the loader versions

### Expected behavior

It should show all the versions up to 0.22.0 beta 1

### System information

Windows 11
App version 0.6.0

### Additional context

![image](https://github.com/modrinth/theseus/assets/39657565/7f8ec594-47d5-41f1-9d15-d4c90ad36d25)

**Comment by triphora** [comment] 2023-11-06 02:20
Scroll down, it's a known bug that's already fixed locally and doesn't actually have anything to do with theseus. Duplicate of #855

**Closed by triphora** 2023-11-06 02:20 UTC
Labels: bug
