### ISSUE TITLE
Duplicate Icons

### ISSUE THREAD

**Issue by Theov0re** [modrinth/theseus#183] opened 2023-06-21 05:46 UTC
### Describe the bug

**Enough said.**
![image](https://github.com/modrinth/theseus/assets/130942503/713d8643-0e9a-4e83-9455-bf85e8ae0c39)

### Steps to reproduce

To reproduce...literally just open the application. In case it's an OS issue, I'll note I am using the latest update of Windows 11.

### Expected behavior

Just one set of icons is most definitely enough...

**Comment by Caliel666** [comment] 2023-06-21 07:14
duplicate of #158

**Closed** 2023-06-21 11:02 UTC
