### ISSUE TITLE
Delete search query button while adding mods doesn't work.

### ISSUE THREAD

**Issue by ProjectNexoi** [modrinth/theseus#361] opened 2023-07-25 00:21 UTC
### Describe the bug

When adding mods to a new instance and searching mods via the search bar, the little "X" button on the right side of the bar does not do anything.
None of the search query is cleared, even though I have pressed it repeatedly.

### Steps to reproduce

1. Create a new instance
2. Navigate to "Add Content"
3. Write in the search bar
4. Click the "X" delete button

### Expected behavior

The query should be wiped upon pressing the button, but no such behavior is happening.

### Additional context

Even after restarting the app, no solution was found. I did not attempt to restart the PC.

**Comment by thesuzerain** [comment] 2023-07-26 16:37
Duplicate of #224

**Comment by thesuzerain** [comment] 2023-07-26 16:37
This will be fixed come the next release! Thanks for your report!

**Closed by thesuzerain** 2023-07-26 16:37 UTC
Labels: bug
